apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: petadoption-staging
  namespace: default
spec:
  secretName: petadoption-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  dnsNames:
    - petadoption.ferdeve.fit